App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'app_blog'

urlpatterns = [    
    path('', views.BlogList.as_view(), name='blog_list'),
    path('detail/<str:slug>/', views.blog_detail, name = 'blog_detail'),
    path('create/', views.CreateBlog.as_view(), name = 'create_blog'),
    path('edit/<int:pk>/', views.UpdateBLog.as_view(), name='edit_blog'),
    path('delete/<int:pk>', views.DeleteBlog.as_view(), name='delete_blog'),
    path('liked/<int:pk>', views.liked, name='liked'),
    path('unliked/<int:pk>', views.unliked, name='unliked'),
    path('myrecipe/', views.MyBlogs.as_view(), name='my_blog'),
    
]

App_Login/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView
from . import views

app_name = 'app_login'

urlpatterns = [    
    path('login/', views.log_in, name='login'),
    path('signup/', views.sign_up, name='signup'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change_profile/', views.user_change, name='change_profile'),
    path('change_password/', views.password_change, name='change_password'),
    path('add_profile_pic', views.add_profile_pic, name='add_pro_pic'),
    path('change_profile_pic', views.change_profile_pic, name='change_pro_pic'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('reset_password_confirm/<uidb64>/<token>/', views.CustomPasswordResetComfirmView.as_view(), name = 'reset_password_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(template_name='App_Login/password_reset_complete.html'), name='password_reset_complete'),
]

My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile


class SignUpForm(UserCreationForm):    
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(label= 'Email Address', required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name')



class UserProfileChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'password' in self.fields:
            self.fields.pop('password') #password 필드 숨기기.



class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',) #쉼표 안들어가면 오류 발생. 이유는???


class ResetPasswordForm(forms.Form):
    first_name = forms.CharField(max_length=150, label='First Name')
    last_name = forms.CharField(max_length=150, label='Last Name')
    username = forms.CharField(max_length=150, label = 'Username')
    email = forms.EmailField(label='Email')

App_Login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetConfirmView
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.urls import reverse, reverse_lazy
from django.contrib import messages

from .forms import SignUpForm, UserProfileChangeForm, ProfilePic, ResetPasswordForm
 



def sign_up(request):
    form = SignUpForm()
    
    registered = False

    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True

    dict = {'form':form, 'registered':registered}
    return render(request, 'App_Login/signup.html', context = dict)



def log_in(request):
    form = AuthenticationForm()
    
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect(reverse('index'))

    dict = {'form':form}
    return render(request, 'App_Login/login.html', context=dict)



@login_required
def log_out(request):
    logout(request)
    return redirect(reverse('index'))


@login_required
def profile(request):
    return render(request,'App_Login/profile.html', context={})


@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChangeForm(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChangeForm(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            messages.success(request,'Profile Changed Successfully')
            return redirect('app_login:profile')#form = UserProfileChangeForm(instance = current_user)

    return render(request, 'App_Login/change_profile.html', context={'form':form})



@login_required
def password_change(request):    
    current_user = request.user
    form = PasswordChangeForm(user=current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=current_user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Password Changed Successfully')
            return redirect('app_login:login')
        
    return render(request, 'App_Login/pass_change.html', context={'form':form})


@login_required
def add_profile_pic(request):    
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            messages.success(request, "Profile Picture Added Successfully.")
            return redirect('app_login:profile')


    return render(request, 'App_Login/pro_pic_add.html', context={'form':form})


@login_required
def change_profile_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return redirect('app_login:profile')


    return render(request, 'App_Login/pro_pic_add.html', context={'form':form})


def reset_password(request):
    form = ResetPasswordForm()
    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            
            try:
                user = User.objects.get(first_name=first_name, last_name=last_name,
                                        username=username, email=email)
                if user:
                    if user.is_active:
                        token = default_token_generator.make_token(user)
                        uidb64 = urlsafe_base64_encode(force_bytes(user.id))
                        return redirect('app_login:reset_password_confirm', uidb64=uidb64, token=token)
                    else:
                        messages.error(request, "This user is not active.")
                else:
                    messages.error(request, "No user found with the provided informations.")
                    
            except:        
                messages.error(request, "No user found with the provided informations.")

    return render(request, 'App_Login/password_reset_form.html', context = {'form':form})
        

class CustomPasswordResetComfirmView(PasswordResetConfirmView):
    template_name = 'App_Login/password_reset_complete.html'
    success_url = reverse_lazy('app_login:password_reset_comoplete')

templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Change Profile
{% endblock %}

{% block body_block%}
<h2>Update Your Profile </h2>
<div class="container-fluid" style="padding-top: 20px;">
    <form method="POST">
        {{ form | crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">Change</button>
    </form>
    
</div>


{% endblock %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Login
{% endblock %}

{% block body_block%}

{% if loggedin %}
<div class="alert alert-success">
    Login Successfully.
</div>

{% else %}

<h2> Login </h2>

{% if messages %}
<div class="alert alert-success">
    
        {% for message in messages %}
            {{ message }}
        {% endfor %}
      
</div>
{% endif %}  

<form method="POST" style="max-width: 500px;">
    {% csrf_token %}
    {{ form|crispy }}
    
    <br>
    <button type="submit" class="btn btn-success btn-sm">Log in</button>

</form>
<br>

<p>Do you have no account? <a href="{% url 'app_login:signup' %}">Sign up</a></p>
<p>Do you forget password? <a href="{% url 'app_login:reset_password' %}">Forget password</a></p>

{% endif %}

{% endblock %}

templates/App_Login/pass_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Change Password
{% endblock %}

{% block body_block%}

<!-- {% if changed %}
<div class="alert alert-success">
    Changed Password Successfully. <a href="{% url 'app_login:login' %}">Login Again.</a>
</div>
{% endif %} -->


<h2>Change Your Password </h2>
<div class="container-fluid" style="padding-top: 20px;">
    <form method="POST">
        {{ form | crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">Change</button>
    </form>
    
</div>


{% endblock %}

templates/App_Login/password_reset_complete.html
{% extends 'base.html' %}
<!-- {% load static %} -->

{% block title %}
Password Reset complete
{% endblock %}


{% block body_block %}

<h2> Password Reset Completed Successfully.</h2>
<p><a href="{% url 'app_login:login' %}">Login Here.</a></p>

{% endblock %}

templates/App_Login/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<!-- {% load static %} -->

{% block title %}
Password Reset Confirm
{% endblock %}


{% block body_block %}
<form method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-primary btn-sm">Reset Password</button>
</form>

{% endblock %}

templates/App_Login/password_reset_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<!-- {% load static %} -->

{% block title %}
Password Reset
{% endblock %}


{% block body_block %}

{% if messages %}
<div class="alert alert-danger">
    
    {% for message in messages %}
        {{ message }}
    {% endfor %}
  
</div>
{% endif %}

<form method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
    
</form>

{% endblock %}

templates/App_Login/pro_pic_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Change Profile Picture
{% endblock %}

{% block body_block%}

<h2>Change Your Profile Picture </h2>
<div class="container-fluid" style="padding-top: 20px;">
    <form method="POST" enctype="multipart/form-data">
        {{ form | crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">Change</button>
    </form>
    
</div>


{% endblock %}

templates/App_Login/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Profile
{% endblock %}

{% block body_block%}
<h2>Your Profile </h2>

{% if messages %}
<div class="alert alert-success">
    
        {% for message in messages %}
            {{ message }}
        {% endfor %}
      
</div>
{% endif %} 



<div class="container-fluid" style="padding-top: 20px;">
    {% if user.user_profile %}
        <img src="/media/{{ user.user_profile.profile_pic }}" class="rounded-circle" width = 120px alt="">
        <br><br>
        <p>
            <a href="{% url 'app_login:change_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
        </p>
    {% else %}
        <img src="/media/download.jpg" class="rounded-circle"  width = 120px  alt="">
        <br><br>
        <p>
            <a href="{% url 'app_login:add_pro_pic' %}" class="btn btn-info btn-sm">Add Profile Picture</a>
        </p>
    {% endif %}
    
    <p>Username : {{ user.username }}</p>
    <p>Email Address : {{ user.email }}</p>
    <p>Name : {{ user.first_name }} {{user.last_name }}</p>
    <br>
    <a class="btn btn-warning btn-sm" href="{% url 'app_login:change_profile' %}">Update Your Profile</a>
    <a class="btn btn-warning btn-sm" href="{% url 'app_login:change_password' %}">Update Your Password</a>
</div>
<div>
    
</div>


{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Create New Account
{% endblock %}

{% block body_block%}
{% if registered %}

<div class="alert alert-success">
    Account Created Successfully. <a href="{% url 'app_login:login' %}">Login</a>
</div>

{% else %}

<h2> Create New Account</h2>
<form method="POST" style="max-width: 500px;">
    {% csrf_token %}
    {{ form|crispy }}
    
    <br>
    <button type="submit" class="btn btn-success btn-sm">Sign Up</button>

</form>
<br>

<p>Already have an account? <a href="{% url 'app_login:login' %}">Login</a></p>

{% endif %}

{% endblock %}