App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'app_blog'

urlpatterns = [    
    path('', views.BlogList.as_view(), name='blog_list'),
    path('detail/<str:slug>/', views.blog_detail, name = 'blog_detail'),
    path('create/', views.CreateBlog.as_view(), name = 'create_blog'),
    path('edit/<int:pk>/', views.UpdateBLog.as_view(), name='edit_blog'),
    path('delete/<int:pk>', views.DeleteBlog.as_view(), name='delete_blog'),
    path('liked/<int:pk>', views.liked, name='liked'),
    path('unliked/<int:pk>', views.unliked, name='unliked'),
    path('myrecipe/', views.MyBlogs.as_view(), name='my_blog'),
    
]

App_Login/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView
from . import views

app_name = 'app_login'

urlpatterns = [    
    path('login/', views.log_in, name='login'),
    path('signup/', views.sign_up, name='signup'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change_profile/', views.user_change, name='change_profile'),
    path('change_password/', views.password_change, name='change_password'),
    path('add_profile_pic', views.add_profile_pic, name='add_pro_pic'),
    path('change_profile_pic', views.change_profile_pic, name='change_pro_pic'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('reset_password_confirm/<uidb64>/<token>/', views.CustomPasswordResetComfirmView.as_view(), name = 'reset_password_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(template_name='App_Login/password_reset_complete.html'), name='password_reset_complete'),
]

My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{%block title%}Blog Page{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" integrity="sha384-tViUnnbYAV00FLIhhi3v/dWt3Jxw4gZQcNoSCxCIFNJVCx7/D55/wXsrNIRANwdD" crossorigin="anonymous">
    <style>
      .image-container { width:100%; position:relative; padding-top:75%; overflow:hidden;}
      .image-container img{position:absolute; top:0; left:0; width:100%; height: 100%; object-fit:cover; object-position:center;}
      .text-container {margin-top:10px; display:-webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; overflow: hidden; text-overflow: ellipsis;}
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <span class="navbar-brand">Make Korean Food!</span>          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
              
              {% if user.is_authenticated %}
              <a class="nav-link active" href="{% url 'app_blog:create_blog' %}">Write Recipe</a>
              <a class="nav-link active" href="{% url 'app_blog:my_blog' %}">My Recipe</a>
              <div class="nav-item dropdow active">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{user.username}}
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'app_login:profile' %}">Your Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'app_login:logout' %}">Logout</a></li>                  
                </ul>
              </div>
              
              
              
              {% else %}
              
              <a class="nav-link active" href="{% url 'app_login:signup' %}">Sign Up</a>
              <a class="nav-link active" href="{% url 'app_login:login' %}">Login</a>
              
              {% endif %}


              

            
            </div>
          </div>
        </div>
      </nav>

      <div class="container-fluid" style="padding-top: 20px;">
        {% block body_block %}
        Blog Content
        {% endblock %}

      </div>
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>