App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'app_blog'

urlpatterns = [    
    path('', views.BlogList.as_view(), name='blog_list'),
    path('detail/<str:slug>/', views.blog_detail, name = 'blog_detail'),
    path('create/', views.CreateBlog.as_view(), name = 'create_blog'),
    path('edit/<int:pk>/', views.UpdateBLog.as_view(), name='edit_blog'),
    path('delete/<int:pk>', views.DeleteBlog.as_view(), name='delete_blog'),
    path('liked/<int:pk>', views.liked, name='liked'),
    path('unliked/<int:pk>', views.unliked, name='unliked'),
    path('myrecipe/', views.MyBlogs.as_view(), name='my_blog'),
    
]

My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name='Put a Title')
    slug = models.SlugField(max_length=264, unique= True)
    blog_content = models.TextField(verbose_name="What is on your mind?")
    blog_image = models.ImageField(upload_to='blog_image', verbose_name="Blog Image")
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ['-publish_date'] #이런 식으로 ordering을 fix 하는 방법도 있음. views.py에서 하거나 여기서 하거나.

    def __str__(self):
        return self.blog_title



class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add = True)


    class Meta:
        ordering = ['-comment_date'] #이런 식으로 ordering을 fix 하는 방법도 있음. views.py에서 하거나 여기서 하거나.

    def __str__(self):
        return self.comment


class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="liker_user")


    

App_Blog/forms.py
from django import forms
from .models import Blog, Comment, Likes


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment', )

App_Blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView, TemplateView
from .models import Blog, Comment, Likes
from .forms import CommentForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required #for def function
from django.contrib.auth.mixins import LoginRequiredMixin #for class view
import uuid



class MyBlogs(TemplateView, LoginRequiredMixin):
    template_name = 'App_Blog/my_blogs.html'



class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'App_Blog/blog_list.html'
    #queryset = Blog.objects.order_by('-publish_date') #-publish_date : descending order


class CreateBlog(CreateView, LoginRequiredMixin):    
    model = Blog
    fields = ('blog_title','blog_content', 'blog_image')
    template_name = 'App_Blog/create_blog.html'


    def form_valid(self, form):
        blog_obj = form.save(commit=False) #commit = False means "hold data"
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = f"{title.replace(' ', '-')}-{uuid.uuid4()}" #가상의 id를 임의로 만들어내서 붙여줌. 동일한 user의 블로그들을 구분하기 위함.
        blog_obj.save()
        return redirect('index')
        


class UpdateBLog(UpdateView, LoginRequiredMixin):
    model = Blog
    fields = ('blog_title','blog_content', 'blog_image')
    template_name = 'App_Blog/edit_blog.html'
    
    def get_success_url(self, **kwargs):
        return reverse_lazy('app_blog:blog_detail', kwargs={'slug':self.object.slug})

   

class DeleteBlog(DeleteView, LoginRequiredMixin):
    model = Blog
    template_name = 'App_Blog/delete_confirm.html'
    success_url=reverse_lazy('index')
    
    


    


def blog_detail(request, slug):
    blog = Blog.objects.get(slug=slug)    
    comment_form = CommentForm()
    liked = False
    
    if request.user.is_authenticated:       
        already_liked = Likes.objects.filter(blog=blog, user=request.user)
        if already_liked:
            liked = True
        

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment_obj = comment_form.save(commit=False)
            comment_obj.user = request.user
            comment_obj.blog = blog
            comment_obj.save()
            return redirect('app_blog:blog_detail', slug=slug)


    return render(request, 'App_Blog/blog_details.html', context={'blog':blog, 'comment_form':comment_form, 'liked':liked})



@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)

    if not already_liked:
        liked_post = Likes(blog=blog, user=user)
        liked_post.save()
    
    return redirect('app_blog:blog_detail', slug=blog.slug)
    

@login_required
def unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    if already_liked:
        already_liked.delete()

    return redirect('app_blog:blog_detail', slug=blog.slug)

templates/App_Blog/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<!-- {% load static %} -->

{% block title %}
Blog Details
{% endblock %}


{% block body_block %}
<div class="row">
    <div class="col-sm-8">
        <h2>{{ blog.blog_title}}</h2>
        <h4>Posted by {{blog.author}}</h4>
        <i><h6>Published on {{ blog.publish_date}} </h6></i>
        <i><h6>Updated on {{ blog.update_date }}</h6></i>
        <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>
    </div>

    <div class="col-sm-4" style="padding-bottom: 20px;">
        <img src="/media/{{ blog.blog_image }}" width="100%">
    </div>
    {{ blog.blog_content | linebreaks }}
</div>


<a href="{% url 'index'%}" class="btn btn-primary btn-sm">Go Home</a>


<hr>
{% if user.is_authenticated %}
    {% if not liked %}
    <a href="{% url 'app_blog:liked' pk=blog.pk %}" class="btn btn-primary btn-sm" style="margin-right: 1em;">
        <i class="bi bi-hand-thumbs-up"></i>
    </a>
    {% else %}
    <a href="{% url 'app_blog:unliked' pk=blog.pk %}" class="btn btn-primary btn-sm">
        <i class="bi bi-hand-thumbs-up-fill"></i>
    </a>
    {% endif %}
{% endif %}

<div class = "row" style="padding-top: 20px;">
    <div class="col-sm-6">
        <h5>Comments:</h5>        
        
        {% for comment in blog.blog_comment.all %}
            <p><a href="#">{{comment.user}}</a><br>
            <B>{{ comment.comment }}</B><br>
            <i>{{ comment.comment_date }}</i></p>
        {% endfor %}        
        
    </div>
    
    <div class="col-sm-6">
        {% if user.is_authenticated %}
        <form method="POST">
            {% csrf_token%}
            {{ comment_form | crispy }}
            <button type="submit" class="btn btn-primary btn-sm">Comment</button>
        </form>
        {% endif %}
    </div>
</div>

<br><br><br>
{% endblock %}

templates/App_Blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
<!-- {% load static %} -->

{% block title %}
Home
{% endblock %}


{% block body_block %}

{% for blog in blogs %}

<h3>{{ blog.blog_title }}</h3>
<h6><i>{{ blog.publish_date }} 
    {% if blog.publish_date != blog.update_date %}, modified on {{ blog.update_date }}{% endif %} 
</i></h6>

<div class="row" style="padding-bottom: 20px;">
    <div class="col-sm-4 col-ml-4 col-lg-3">
        <div class="image-container">
            <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
        </div>
    </div>
    
    <div class="col-sm-8">
        <div class="text-container">
            {{ blog.blog_content | linebreaks }} 
        </div>
       <p>
        <a href="{% url 'app_blog:blog_detail' slug=blog.slug %}">Read more</a>
       </p><!--linkbreaks : 줄바꿈 해주는 필터. 이거 추가 안하면 하나의 paragraph 처럼 출력됨-->
       <h6>Posted by <a href="#">{{ blog.author.username }}</a></h6>
       <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>
       
    </div>
    

</div>

{% endfor %}

{% endblock %}

templates/App_Blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<!-- {% load static %} -->

{% block title %}
Create Blog
{% endblock %}


{% block body_block %}
<h2> Write New Blog</h2>

<form method ='POST' enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-primary btn-sm">Publish</button>
</form>
<br>

{% endblock %}

templates/App_Blog/delete_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<!-- {% load static %} -->

{% block title %}
Delete Recipe
{% endblock %}


{% block body_block %}
<h3>Are you sure you want to delete this recipe?</h3>
<p> {{ object.blog_title }}</p>

<form method="POST">
    {% csrf_token %}    
    <button type="submit" class="btn btn-primary btn-sm">Confirm</button>
    <a href="{% url 'index' %}" class="btn btn-secondary btn-sm">Cancel</a>
</form>

{% endblock %}

templates/App_Blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<!-- {% load static %} -->

{% block title %}
Edit Recipe
{% endblock %}


{% block body_block %}


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form | crispy }}
    <button type="submit" class="btn btn-primary btn-sm">Update</button>
</form>

{% endblock %}

templates/App_Blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
<!-- {% load static %} -->

{% block title %}
My Recipes
{% endblock %}


{% block body_block %}


{% if user.post_author.all.count == 0 %}
    <h3>No recipe by {{ user.username }}</h3>

{% else %}

    {% for blog in user.post_author.all %}

    <h3>{{ blog.blog_title }}</h3>
    <h6>{{ blog.publish_date }}</h6>

    <div class="row">
        <div class="col-sm-4">
            <img src="/media/{{blog.blog_image}}" width="100%">
        </div>

        <div class="col-sm-8">
            <p>{{ blog.blog_content | range_filter  | linebreaks }} 
            <a href="{% url 'app_blog:blog_detail' slug=blog.slug %}">Read more</a>
            
            </p><!--linkbreaks : 줄바꿈 해주는 필터. 이거 추가 안하면 하나의 paragraph 처럼 출력됨-->
            <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments    </h6>
            <a href="{% url 'app_blog:edit_blog' pk=blog.pk %}" class="btn btn-info btn-sm" style="margin-right: 1em;">Edit</a>
            <a href="{% url 'app_blog:delete_blog' pk=blog.pk %}" class="btn btn-danger btn-sm">Delete</a>

        </div>
    </div>
    <hr>
    
    {% endfor %}
{% endif %}

{% endblock %}